<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />

    <xacro:property name="cyl_radius" value="0.1" />
    <xacro:property name="cyl_len" value="0.05" />

    <xacro:property name="sph_radius" value="0.05" />

    <xacro:property name="arm_base_radius" value="0.1" />
    <xacro:property name="arm_base_length" value="0.07" />
    <xacro:property name="arm_length" value="0.5" />
    <xacro:property name="third_arm_length" value="0.025" />
    <xacro:property name="arm_radius" value="0.03" />

    <xacro:property name="arm_link_cyl_len" value="0.1" />
    <xacro:property name="arm_link_cyl_radius" value="0.04" />

    <xacro:property name="gripper_base_length" value="0.15" />
    <xacro:property name="gripper_base_width" value="0.05" />
    <xacro:property name="gripper_base_height" value="0.02" />

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green" />
        </visual>
        
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>

        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}" xyz="0 0 0" rpy="0 0 0" />
    </link>

    <link name="arm_base_link">
        <visual>
            <geometry>
                <cylinder radius="${arm_base_radius}" length="${arm_base_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        
        <collision>
            <geometry>
                <cylinder radius="${arm_base_radius}" length="${arm_base_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>

        <xacro:wheel_inertia m="0.5" r="${2*arm_base_radius}" h="${2*arm_base_length}" xyz="0 0 0" rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${cyl_radius}" length="${cyl_len}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue" />
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${cyl_radius}" length="${cyl_len}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>

        <xacro:wheel_inertia m="1.0" r="${2*cyl_radius}" h="${2*cyl_len}" xyz="0 0 0" rpy="0 0 0" />
    </link>
    </xacro:macro>

    <xacro:macro name="arm_link" params="postfix l">
        <link name="arm_link_${postfix}">
        <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${l}" />
            </geometry>
            <origin xyz="0 0 ${(l/2)}" rpy="0 0 0" />
            <material name="blue" />
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${arm_radius}" length="${l}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>

        <xacro:wheel_inertia m="0.3" r="${2*arm_radius}" h="${2*l}" xyz="0 0 0" rpy="0 0 0" />
    </link>
    </xacro:macro>

    <xacro:macro name="arm_joint_link" params="postfix">
        <link name="arm_joint_link_${postfix}">
        <visual>
            <geometry>
                <cylinder radius="${arm_link_cyl_radius}" length="${arm_link_cyl_len}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue" />
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${arm_link_cyl_radius}" length="${arm_link_cyl_len}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>

        <xacro:wheel_inertia m="0.3" r="${2*arm_link_cyl_radius}" h="${2*arm_link_cyl_len}" xyz="0 0 0" rpy="0 0 0" />
    </link>
    </xacro:macro>

    <xacro:arm_joint_link postfix="first" />
    <xacro:arm_joint_link postfix="second" />

    <xacro:arm_link postfix="first" l="${arm_length}" />
    <xacro:arm_link postfix="second" l="${arm_length}" />

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />
    <xacro:wheel_link prefix="front_left" />
    <xacro:wheel_link prefix="front_right" />

    <xacro:macro name="gripper" params="prefix">
        <link name="${prefix}_gripper">
        <visual>
            <geometry>
                <box size="${gripper_base_length} ${gripper_base_width} ${gripper_base_height}" />
            </geometry>
            <origin xyz="${-(gripper_base_length/2)} 0 0" rpy="0 0 0" />
            <material name="green" />
        </visual>

        <collision>
            <geometry>
                <box size="${gripper_base_length} ${gripper_base_width} ${gripper_base_height}" />
            </geometry>
            <origin xyz="${-(gripper_base_length/2)} 0 0" rpy="0 0 0" />
        </collision>

        <xacro:box_inertia m="0.2" l="${2*gripper_base_length}" w="${2*gripper_base_width}" h="${2*gripper_base_height}" xyz="0 0 0" rpy="0 0 0" />
    </link>
    </xacro:macro>

    <xacro:gripper prefix="right" />
    <xacro:gripper prefix="left" />

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${base_height}" rpy="0 0 0" /> 
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-((base_length/2) - cyl_radius)} ${-((base_width/2) + (cyl_len/2))} ${-(base_height/2)}" rpy="${pi / 2.0} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-((base_length/2) - cyl_radius)} ${(base_width/2) + (cyl_len/2)} ${-(base_height/2)}" rpy="${pi / 2.0} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="${((base_length/2) - cyl_radius)} ${(base_width/2) + (cyl_len/2)} ${-(base_height/2)}" rpy="${pi / 2.0} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="${((base_length/2) - cyl_radius)} ${-((base_width/2) + (cyl_len/2))} ${-(base_height/2)}" rpy="${pi / 2.0} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_arm_base_joint" type="continuous">
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="0 0 ${(base_height/2) + (arm_base_length/2)}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_arm_first_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="arm_link_first" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="${-(pi/2)}" upper="${pi/2}" effort="100" velocity="100" />
    </joint>

    <joint name="arm_link_first_rev_joint" type="fixed">
        <parent link="arm_link_first" />
        <child link="arm_joint_link_first" />
        <origin xyz="0 0 ${arm_length}" rpy="${pi / 2.0} 0 0" />
    </joint>

    <joint name="second_arm_link_joint" type="continuous">
        <parent link="arm_joint_link_first" />
        <child link="arm_link_second" />
        <origin xyz="0 0 0" rpy="${-(pi / 2.0)} 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="arm_link_second_rev_joint" type="continuous">
        <parent link="arm_link_second" />
        <child link="arm_joint_link_second" />
        <origin xyz="0 0 ${arm_length}" rpy="${pi / 2.0} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="gripper_right_joint" type="continuous">
        <parent link="arm_joint_link_second" />
        <child link="right_gripper" />
        <origin xyz="0 0 ${((arm_link_cyl_len/2)-(gripper_base_height/2))}" rpy="0 0 ${-(pi / 2.0)}" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="gripper_left_joint" type="continuous">
        <parent link="arm_joint_link_second" />
        <child link="left_gripper" />
        <origin xyz="0 0 ${-((arm_link_cyl_len/2)-(gripper_base_height/2))}" rpy="0 0 ${-(pi / 2.0)}" />
        <axis xyz="0 1 0" />
    </joint>

</robot>